### ISSUE TITLE
img_src is deprecated

### ISSUE THREAD

**Issue by fajoaq** [Hujjat/shopify-sunrise#4]
Hello buddy, I'm working on my theme and noticing quite a few linting warnings. One of which is that 'img_src' is deprecated. It still works, but the new way to do it is "section.settings.image | image_src: width: 'string', height: 'string'". Only one dimension is required.

There are quite a few instances, I understand if you're too busy to update. If you like, I can do a PR. Cheers

**Comment by Hujjat** [comment]
Hey @fajoaq 

Please send your PR. It's a starter theme and people will customize it anyway. Your change seems to be easy PR. 

Thank you!

**Comment by fajoaq** [comment]
#5 fix deprecated img_url tag

Hopefully I didn't miss anything. Cheers!

**Comment by Hujjat** [comment]
Thank you @fajoaq . I will review it soon and merge it.

**Comment by fajoaq** [comment]
You're most welcome, I have another (more interesting) proposal coming soon. Closing this.
