### ISSUE TITLE
Allow user to change breakpoints

### ISSUE THREAD

**Issue by fajoaq** [Hujjat/shopify-sunrise#6]
:wave: Hello again. I am proposing a means to allow the user to define custom breakpoints without having to rely on a custom tailwind config file. This way the end user can pop into the theme editor and change these values at will.

[ **My contribution would only move the tailwind breakpoints outside of the tailwind config file (using default values), and the theme author can decide whether they want to provide this functionality** ].

### Pros
- End user can change pre-defined breakpoints easily
- **In developmen**t, the css is rebuilt automatically when using Shopify Theme Serve with the '--theme-editor-sync' option

### Cons
- **Outside of development**, must rebuild the css after changing breakpoints through the editor, or [ tailwind ] generated queries will not be updated

### How
I have tested this by adding breakpoints to the settings_schema (e.g, 'breakpoint_lg'), and importing the json data into the tailwind config file from 'settings_data'. (optionally, you can simply add these breakpoints to 'settings_data' directly)
_tailwind.config.js_
```
const settings = require("./config/settings_data.json").current;
const breakpoints = {
  xl: settings.breakpoint_lg + "px",
  lg: settings.breakpoint_lg + "px",
  md: settings.breakpoint_md + "px",
  sm: settings.breakpoint_sm + "px",
  xs: settings.breakpoint_xs + "px",
};
module.exports = {
  content: [/* paths */],
  theme: {
    screens: {
      xl: breakpoints.lg,
      lg: breakpoints.lg,
      md: breakpoints.md,
      sm: breakpoints.sm,
      xs: breakpoints.xs,
    },
  },
};

```
Of course, you can continue to use tailwind breakpoints, but I wouldn't. My solution is to not use tailwind breakpoints (e.g, md:p-0) wherever possible, and use the settings values directly instead via {% style %} tags. I took this approach because I was having zero luck getting css vars to work inside the config file. 

This is purely optional, tailwind breakpoints will continue to work as intended. I think it's worth it to allow the user to change these values as needed. What do you think?

Cheers

Edit; I've noted that while you work on the theme settings schema, you'll want to use Shopify Theme Serve without the sync option (or whatever is equivalent)

**Comment by Hujjat** [comment]
Hey @fajoaq 

Thank you for the details explanation!

Your approach is great to handle custom breakpoints. But we don't normally give end-user set breakpoints. If a Shopify customer wants to change breakpoints, they probably have a developer who can do it. 

Also, this theme is for tutorials only. People who want to create a fully functional theme will use your approach. 

Thank you 🙌

**Comment by fajoaq** [comment]
Valid point. Thanks for looking at my suggestion 😄
